{ ... }:
{
  /**
  Provides a `hostIdentity` set that lets hosts configure the a
  canonical name, description, state version, and primary user of a NixOS host.
  The `name` field is wired through to `networking.hostName`
  automatically.

  This module is included in every host generated by the registry,
  so callers only need to pass the identity values once at the
  top level.
  */
  flake.modules.nixos.host-identity =
    { config, lib, ... }:
    {
      options.hostIdentity = {
        name = lib.mkOption {
          type = lib.types.nonEmptyStr;
          readOnly = true;
          description = "The canonical host and NixOS configuration name.";
        };

        description = lib.mkOption {
          type = lib.types.nonEmptyStr;
          readOnly = true;
          description = "A human-readable description of this host.";
        };

        primaryUser = lib.mkOption {
          type = lib.types.nonEmptyStr;
          readOnly = true;
          description = "The primary interactive user of this host.";
        };

        stateVersion = lib.mkOption {
          type = lib.types.nonEmptyStr;
          readOnly = true;
          description = "The NixOS state version shared with this host's user environments by default.";
        };
      };

      config.networking.hostName = config.hostIdentity.name;
    };
}
